CREATE TABLE public.councils (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 120),
	display_name TEXT,
	year TEXT,
	password_salt TEXT NOT NULL,
	password_hash TEXT NOT NULL,
	logo_url TEXT,
	logo_key TEXT,
	logo_mime_type TEXT,
	logo_original_name TEXT,
	handlingsplan_url TEXT,
	handlingsplan_key TEXT,
	handlingsplan_mime_type TEXT,
	handlingsplan_original_name TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.council_tema (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	council_id BIGINT NOT NULL REFERENCES public.councils(id) ON DELETE CASCADE,
	name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 100),
	color TEXT,
	allow_add BOOLEAN NOT NULL DEFAULT true,
	allow_change BOOLEAN NOT NULL DEFAULT true,
	allow_remove BOOLEAN NOT NULL DEFAULT true,
	position INTEGER NOT NULL DEFAULT 0,
	UNIQUE (council_id, name)
);

CREATE TABLE public.innspill (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	council_id BIGINT NOT NULL REFERENCES public.councils(id) ON DELETE CASCADE,
	action_type TEXT NOT NULL CHECK (action_type IN ('add', 'change', 'remove')),
	tema TEXT NOT NULL CHECK (length(trim(tema)) BETWEEN 1 AND 100),
	punkt_nr INTEGER NOT NULL CHECK (punkt_nr > 0),
	underpunkt_nr INTEGER CHECK (underpunkt_nr > 0),
	formuler_punkt TEXT,
	endre_fra TEXT,
	endre_til TEXT,
	status TEXT NOT NULL DEFAULT 'ny' CHECK (status IN ('ny', 'under_behandling', 'vedtatt', 'godkjent', 'avvist')),
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX council_tema_council_position_idx
	ON public.council_tema (council_id, position, id);

CREATE INDEX innspill_council_created_idx
	ON public.innspill (council_id, created_at, id);

CREATE TRIGGER councils_updated_at
	BEFORE UPDATE ON public.councils
	FOR EACH ROW EXECUTE FUNCTION system.update_updated_at();

CREATE TRIGGER innspill_updated_at
	BEFORE UPDATE ON public.innspill
	FOR EACH ROW EXECUTE FUNCTION system.update_updated_at();

ALTER TABLE public.councils ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.council_tema ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.innspill ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.councils FROM anon, authenticated;
REVOKE ALL ON public.council_tema FROM anon, authenticated;
REVOKE ALL ON public.innspill FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.councils_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.council_tema_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.innspill_id_seq FROM anon, authenticated;
